import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App ASdasd",
  description: "Generated by create next app",
};

const page = () => {
  return <div style={{minHeight: "100vh", background: "lightgray", paddingTop: "24rem"}} >Contact page</div>;
};

export default page;
